import { useEffect, useState } from "react";
import { Plus, Target } from "lucide-react";
import Seo from "@/components/seo/Seo";
import { breadcrumbSchema } from "@/components/seo/schema";

import GoalCard from "@/components/goals/GoalCard";
import CreateGoalModal from "@/components/goals/CreateGoalModal";
import AddContributionModal from "@/components/goals/AddContributionModal";

import {
  getPersonalGoals,
  deletePersonalGoal,
  completePersonalGoal,
} from "@/services/personalGoals";

export default function GoalsPage() {
  const [goals, setGoals] = useState([]);
  const [createOpen, setCreateOpen] = useState(false);
  const [contributionGoal, setContributionGoal] = useState(null);

  useEffect(() => {
    const refresh = () => setGoals(getPersonalGoals());
    refresh();
    window.addEventListener("finaiw:personal-goals-updated", refresh);
    return () => window.removeEventListener("finaiw:personal-goals-updated", refresh);
  }, []);

  const active = goals.filter((g) => !g.completed);
  const completed = goals.filter((g) => g.completed);

  return (
    <div className="mx-auto max-w-6xl px-5 py-14 sm:px-8 lg:px-12">
      <Seo
        title="My Goals — Track Real Savings Progress"
        description="Set a real financial goal, log real contributions, and track your progress — nothing generated by a calculator, entirely yours."
        path="/goals"
        keywords="savings goal tracker, financial goal planner, goal tracking app"
        jsonLd={breadcrumbSchema([
          { name: "Home", path: "/" },
          { name: "Goals", path: "/goals" },
        ])}
      />

      <div className="flex flex-wrap items-end justify-between gap-4">
        <div>
          <span className="text-[12px] font-black uppercase tracking-wide text-emerald-700">Your Plan</span>
          <h1 className="mt-3 text-4xl font-black text-slate-950">My Goals</h1>
          <p className="mt-2 max-w-lg text-slate-500">
            Set a real goal, log real contributions as you save toward it. Nothing here comes from a calculator —
            it's entirely yours.
          </p>
        </div>
        <button
          onClick={() => setCreateOpen(true)}
          className="inline-flex items-center gap-2 rounded-xl bg-emerald-800 px-6 py-3.5 text-[13px] font-black text-white shadow-[0_16px_35px_rgba(4,120,87,.2)] transition hover:-translate-y-0.5 hover:bg-emerald-900"
        >
          <Plus size={16} /> Create a Goal
        </button>
      </div>

      {active.length === 0 && completed.length === 0 ? (
        <div className="mt-12 rounded-3xl border border-dashed border-slate-300 bg-white py-16 text-center">
          <div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-emerald-50">
            <Target className="text-emerald-700" size={26} />
          </div>
          <h2 className="mt-5 text-2xl font-bold text-slate-950">No goals yet</h2>
          <p className="mx-auto mt-3 max-w-sm text-slate-500">
            Create your first goal — give it a name, a target amount, and start logging what you save toward it.
          </p>
          <button
            onClick={() => setCreateOpen(true)}
            className="mt-8 inline-flex items-center gap-2 rounded-xl bg-emerald-800 px-6 py-3.5 text-[13px] font-black text-white transition hover:bg-emerald-900"
          >
            <Plus size={16} /> Create a Goal
          </button>
        </div>
      ) : (
        <>
          {active.length > 0 && (
            <section className="mt-10 space-y-5">
              <h2 className="text-xl font-black text-slate-950">Active Goals</h2>
              <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">
                {active.map((goal) => (
                  <GoalCard
                    key={goal.id}
                    goal={goal}
                    onAddMoney={setContributionGoal}
                    onComplete={(g) => completePersonalGoal(g.id)}
                    onDelete={(g) => deletePersonalGoal(g.id)}
                  />
                ))}
              </div>
            </section>
          )}

          {completed.length > 0 && (
            <section className="mt-12 space-y-5">
              <h2 className="text-xl font-black text-slate-950">Completed</h2>
              <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">
                {completed.map((goal) => (
                  <GoalCard
                    key={goal.id}
                    goal={goal}
                    onAddMoney={setContributionGoal}
                    onComplete={() => {}}
                    onDelete={(g) => deletePersonalGoal(g.id)}
                  />
                ))}
              </div>
            </section>
          )}
        </>
      )}

      <CreateGoalModal open={createOpen} onClose={() => setCreateOpen(false)} />
      <AddContributionModal
        open={!!contributionGoal}
        goal={contributionGoal}
        onClose={() => setContributionGoal(null)}
      />
    </div>
  );
}
