import { useEffect, useState } from "react";
import { Plus, Target } from "lucide-react";
import Seo from "@/components/seo/Seo";
import { breadcrumbSchema } from "@/components/seo/schema";

import GoalCard from "@/components/goals/GoalCard";
import CreateGoalModal from "@/components/goals/CreateGoalModal";
import AddContributionModal from "@/components/goals/AddContributionModal";

import {
  getPersonalGoals,
  deletePersonalGoal,
  completePersonalGoal,
} from "@/services/personalGoals";

export default function GoalsPage() {
  const [goals, setGoals] = useState([]);
  const [createOpen, setCreateOpen] = useState(false);
  const [contributionGoal, setContributionGoal] = useState(null);

  useEffect(() => {
    const refresh = () => setGoals(getPersonalGoals());
    refresh();
    window.addEventListener("finaiw:personal-goals-updated", refresh);
    return () => window.removeEventListener("finaiw:personal-goals-updated", refresh);
  }, []);

  const active = goals.filter((g) => !g.completed);
  const completed = goals.filter((g) => g.completed);

  return (
    <div className="bg-[#eef1ec] dark:bg-[#0b1210]">
      <div className="mx-auto max-w-6xl px-5 py-16 sm:px-8 lg:px-12">
        <Seo
          title="My Goals — Track Real Savings Progress"
          description="Set a real financial goal, log real contributions, and track your progress — nothing generated by a calculator, entirely yours."
          path="/goals"
          keywords="savings goal tracker, financial goal planner, goal tracking app"
          jsonLd={breadcrumbSchema([
            { name: "Home", path: "/" },
            { name: "Goals", path: "/goals" },
          ])}
        />

        <div className="flex flex-wrap items-end justify-between gap-4">
          <div>
            <span className="text-[13px] font-semibold text-[#047857] dark:text-[#34d399]">Your plan</span>
            <h1 className="font-display mt-3 text-4xl font-extrabold text-[#111814] dark:text-[#eef1ec]">My Goals</h1>
            <p className="mt-2 max-w-lg text-[15px] leading-7 text-[#111814]/65 dark:text-[#eef1ec]/65">
              Set a real goal, log real contributions as you save toward it. Nothing here comes from a calculator —
              it's entirely yours.
            </p>
          </div>
          <button
            onClick={() => setCreateOpen(true)}
            className="inline-flex h-11 flex-shrink-0 items-center gap-2 bg-[#047857] px-5 text-[13px] font-semibold text-white transition hover:bg-[#065f46]"
          >
            <Plus size={16} /> Create a Goal
          </button>
        </div>

        {active.length === 0 && completed.length === 0 ? (
          <div className="mt-12 border border-[#111814]/12 bg-[#ffffff] py-16 text-center dark:border-[#eef1ec]/12 dark:bg-[#0b1210]">
            <Target className="mx-auto text-[#047857] dark:text-[#34d399]" size={28} />
            <h2 className="font-display mt-5 text-2xl font-bold text-[#111814] dark:text-[#eef1ec]">No goals yet</h2>
            <p className="mx-auto mt-3 max-w-sm text-[15px] leading-7 text-[#111814]/65 dark:text-[#eef1ec]/65">
              Create your first goal — give it a name, a target amount, and start logging what you save toward it.
            </p>
            <button
              onClick={() => setCreateOpen(true)}
              className="mt-8 inline-flex h-11 items-center gap-2 bg-[#047857] px-5 text-[13px] font-semibold text-white transition hover:bg-[#065f46]"
            >
              <Plus size={16} /> Create a Goal
            </button>
          </div>
        ) : (
          <>
            {active.length > 0 && (
              <section className="mt-10 space-y-5">
                <h2 className="font-display text-xl font-bold text-[#111814] dark:text-[#eef1ec]">Active Goals</h2>
                <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">
                  {active.map((goal) => (
                    <GoalCard
                      key={goal.id}
                      goal={goal}
                      onAddMoney={setContributionGoal}
                      onComplete={(g) => completePersonalGoal(g.id)}
                      onDelete={(g) => deletePersonalGoal(g.id)}
                    />
                  ))}
                </div>
              </section>
            )}

            {completed.length > 0 && (
              <section className="mt-12 space-y-5">
                <h2 className="font-display text-xl font-bold text-[#111814] dark:text-[#eef1ec]">Completed</h2>
                <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">
                  {completed.map((goal) => (
                    <GoalCard
                      key={goal.id}
                      goal={goal}
                      onAddMoney={setContributionGoal}
                      onComplete={() => {}}
                      onDelete={(g) => deletePersonalGoal(g.id)}
                    />
                  ))}
                </div>
              </section>
            )}
          </>
        )}

        <CreateGoalModal open={createOpen} onClose={() => setCreateOpen(false)} />
        <AddContributionModal
          open={!!contributionGoal}
          goal={contributionGoal}
          onClose={() => setContributionGoal(null)}
        />
      </div>
    </div>
  );
}
